AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Forgot Password API requirements

Parameters:
  AppName:
    Type: String
  ServiceName:
    Type: String
  Stage:
    Type: String
  ForgotPasswordApiGatewayRoleArn:
    Type: String
  ForgotPasswordFunctionArn:
    Type: String
  ConfirmForgotPasswordFunctionArn:
    Type: String

Resources:
  ForgotPasswordApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Name: !Sub "${AppName}-${Stage}-${ServiceName}-forgot-password-api"
      TracingEnabled: true
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        openapi: 3.0.3
        info:
          version: 1.0.0
          title: !Sub "${AppName}-${Stage}-${ServiceName}-forgot-password-api"
          description: Public forgot password API

        paths:
          /forgot-password:
            post:
              x-amazon-apigateway-integration:
                credentials: !Ref ForgotPasswordApiGatewayRoleArn
                httpMethod: POST
                type: aws_proxy
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ForgotPasswordFunctionArn}/invocations"
              responses:
                '200':
                  description: Successful
                  content:
                    application/json:
                      schema:
                        type: object
            options:
              responses:
                "200":
                  description: "CORS response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                type: "mock"
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent,X-Amzn-Trace-Id'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                    responseTemplates:
                      application/json: "{}"

          /confirm-forgot-password:
            post:
              x-amazon-apigateway-integration:
                credentials: !Ref ForgotPasswordApiGatewayRoleArn
                httpMethod: POST
                type: aws_proxy
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConfirmForgotPasswordFunctionArn}/invocations"
              responses:
                '200':
                  description: Successful
                  content:
                    application/json:
                      schema:
                        type: object
            options:
              responses:
                "200":
                  description: "CORS response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                type: "mock"
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent,X-Amzn-Trace-Id'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                    responseTemplates:
                      application/json: "{}"

  ForgotPasswordApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ForgotPasswordFunctionArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ForgotPasswordApi}/${Stage}/*/*"

  ConfirmForgotPasswordApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ConfirmForgotPasswordFunctionArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ForgotPasswordApi}/${Stage}/*/*"

Outputs:
  ForgotPasswordApiUrl:
    Description: "Forgot Password API endpoint URL"
    Value: !Sub "https://${ForgotPasswordApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/forgot-password"
  ForgotPasswordApiId:
    Description: "Forgot Password API ID"
    Value: !Ref ForgotPasswordApi
  ConfirmForgotPasswordApiUrl:
    Description: "Confirm Forgot Password API endpoint URL"
    Value: !Sub "https://${ForgotPasswordApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/confirm-forgot-password"
  ConfirmForgotPasswordApiId:
    Description: "Confirm Forgot Password API ID"
    Value: !Ref ForgotPasswordApi