AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for Forgot password

Parameters:
  AppName:
    Type: String
  Stage:
    Type: String
  ServiceName:
    Type: String
  AwsLambdaPowertoolsPythonLayer:
    Type: String
    
Globals:
  Function:
    Timeout: 300
    MemorySize: 1024
    Layers:
      - !Ref PythonRequirementsLayer
      - !Ref UtilsLayer
      - !Ref AwsLambdaPowertoolsPythonLayer
    Runtime: python3.10
    Tracing: Active
    Architectures:
      - x86_64
    Environment:
      Variables:
        APP_NAME: !Ref AppName
        STAGE: !Ref Stage

Resources:
  ForgotPasswordServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-${Stage}-${ServiceName}-forgot-password-role"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSLambdaExecute"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${AppName}-${Stage}-${ServiceName}-forgot-password-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Cognito permissions
              - Effect: Allow
                Action:
                  - cognito-idp:InitiateAuth
                  - cognito-idp:AdminGetUser
                  - cognito-idp:RespondToAuthChallenge
                  - cognito-idp:ConfirmForgotPassword
                  - cognito-idp:ForgotPassword
                  - cognito-idp:ChangePassword
                Resource: "*"
              
              # SSM Parameter Store permissions
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/many-cards/${Stage}/POOL_ID"
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/many-cards/${Stage}/CLIENT_ID"
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/many-cards/${Stage}/CLIENT_SECRET"
              
              # KMS permissions
              - Effect: Allow 
                Action:
                  - kms:Decrypt
                Resource: "*"
              
              # DynamoDB permissions - SPECIFIC to your table
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: 
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/many-cards-${Stage}-main-table"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/many-cards-${Stage}-main-table/index/*"

  ForgotPasswordApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-${Stage}-${ServiceName}-api-gateway-role"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/CloudWatchFullAccess"
        - "arn:aws:iam::aws:policy/AWSLambdaExecute"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${AppName}-${Stage}-${ServiceName}-api-gateway-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: 
                  - !GetAtt ForgotPasswordFunction.Arn
                  - !GetAtt ConfirmForgotPasswordFunction.Arn

  ForgotPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Stage}-${ServiceName}-forgot-password-function"
      Handler: main.handler
      CodeUri: ./src/forgot-password/
      Role: !GetAtt ForgotPasswordServiceRole.Arn
      Description: A simple Lambda function for forgot password.

  ForgotPasswordFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ForgotPasswordFunction}"
      RetentionInDays: 14

  ConfirmForgotPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Stage}-${ServiceName}-confirm-forgot-password-function"
      Handler: main.handler
      CodeUri: ./src/confirm-forgot-password/
      Role: !GetAtt ForgotPasswordServiceRole.Arn
      Description: A simple Lambda function for confirming forgot password.

  ConfirmForgotPasswordFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ConfirmForgotPasswordFunction}"
      RetentionInDays: 14

  PythonRequirementsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AppName}-${Stage}-${ServiceName}-python-requirements"
      Description: Dependencies for the auth service Lambda function
      ContentUri: dependencies/requirements/
      CompatibleRuntimes:
        - python3.9
      LicenseInfo: MIT
    Metadata:
      BuildMethod: python3.10

  UtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AppName}-${Stage}-${ServiceName}-utils-layer"
      Description: Utility functions for Lambda
      ContentUri: ./dependencies/utils/
    Metadata:
      BuildMethod: python3.10

  ForgotPasswordApiGateway:
    Type: AWS::Serverless::Application
    Properties:
      Location: api.yml
      Parameters:
        AppName: !Ref AppName
        Stage: !Ref Stage
        ServiceName: !Ref ServiceName
        ForgotPasswordApiGatewayRoleArn: !GetAtt ForgotPasswordApiGatewayRole.Arn
        ForgotPasswordFunctionArn: !GetAtt ForgotPasswordFunction.Arn
        ConfirmForgotPasswordFunctionArn: !GetAtt ConfirmForgotPasswordFunction.Arn

Outputs:
  ForgotPasswordFunctionArn:
    Description: "Forgot Password Function ARN"
    Value: !GetAtt ForgotPasswordFunction.Arn
  ConfirmForgotPasswordFunctionArn:
    Description: "Confirm Forgot Password Function ARN"
    Value: !GetAtt ConfirmForgotPasswordFunction.Arn